name: Rust

on: [push]

jobs:
  build:

    runs-on: {{ matrix.machine }}
    strategy:
      matrix:
        machine: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
